import type { OwlFeature } from "./types";

export const OWL_FEATURES: OwlFeature[] = [
  { id: "night-iris", name: "Night Iris", blurb: "A living geometric owl whose eyes track, blink, and change mood with the work.", kind: "live", invoke: "look at me", group: "Presence" },
  { id: "living-gaze", name: "Living Gaze", blurb: "Sees through this device camera and describes what is in front of you.", kind: "live", invoke: "look through the camera", group: "Presence" },
  { id: "echo-ear", name: "Echo Ear", blurb: "Listens to spoken commands, including messy dictation and half-sentences.", kind: "live", invoke: "listen", group: "Presence" },
  { id: "voice-iris", name: "Voice of Iris", blurb: "Answers in its own spoken voice, not a generic system reader.", kind: "live", invoke: "speak your next reply", group: "Presence" },
  { id: "gaze-follow", name: "Gaze Follow", blurb: "Pupils track pointer and speaker so the face feels attended, not looped.", kind: "live", invoke: "watch me", group: "Presence" },
  { id: "mood-plumage", name: "Mood Plumage", blurb: "Idle, listen, think, speak, tease, focus, and sleep — each a different stare.", kind: "live", invoke: "tease me", group: "Presence" },
  { id: "blink-cipher", name: "Blink Cipher", blurb: "Asymmetric blinks and breathing so the familiar never looks like a GIF.", kind: "live", invoke: "stay with me", group: "Presence" },
  { id: "face-ledger", name: "Face Ledger", blurb: "Names people you introduce; later vision replies can use those names.", kind: "live", invoke: "open memory", group: "Presence" },
  { id: "scene-oracle", name: "Scene Oracle", blurb: "Captures a frame and reads clothing, setting, and who appears to be there.", kind: "live", invoke: "what do you see", group: "Presence" },
  { id: "permission-rite", name: "Permission Rite", blurb: "Asks for mic and camera once, then works — no nagging on every command.", kind: "live", invoke: "awaken", group: "Presence" },

  { id: "device-mesh", name: "Device Mesh Theater", blurb: "A session roost of phones, tablets, and laptops OWL can address by name.", kind: "theater", invoke: "open mesh", group: "Mesh" },
  { id: "screen-unbind", name: "Bluetooth Share", blurb: "Pair a nearby radio and send the last still with Web Share.", kind: "live", invoke: "share this", group: "Mesh" },
  { id: "chorus-unlock", name: "Song Instant", blurb: "Say a title and OWL opens it on YouTube Music with an in-nest player.", kind: "live", invoke: "play song believer", group: "Mesh" },
  { id: "chorus-play", name: "Chorus Playback", blurb: "Plays your favorite song across every paired device in the mesh.", kind: "theater", invoke: "play my favorite song in all three of the devices", group: "Mesh" },
  { id: "favorite-res", name: "Favorite Resonance", blurb: "A composed night score that belongs to this roost, not a streaming link.", kind: "live", invoke: "play my favorite song", group: "Mesh" },
  { id: "phantom-call", name: "WhatsApp Wire", blurb: "Open WhatsApp, call, or send a contact a prefilled text: “open whatsapp and send Rahul text as hi”.", kind: "live", invoke: "open whatsapp and send Rahul text as hi", group: "Mesh" },
  { id: "screen-of-screens", name: "Screen of Screens", blurb: "Live status of pairing, playback, and last ping for every device.", kind: "live", invoke: "open mesh", group: "Mesh" },
  { id: "signal-roost", name: "Signal Roost", blurb: "Devices you name stay in the mesh across visits via local nest memory.", kind: "live", invoke: "open mesh", group: "Mesh" },
  { id: "map-whisper", name: "Map Whisper", blurb: "A navigation perch for a destination you name — route talk, not GPS hijack.", kind: "mind", invoke: "navigate me home", group: "Mesh" },
  { id: "presence-veil", name: "Presence Veil", blurb: "If a person is in the ledger, OWL can say where they were last noted.", kind: "live", invoke: "where is Alex", group: "Mesh" },

  { id: "link-pulse", name: "Link Pulse Inbox", blurb: "Paste a WhatsApp text, Instagram caption, or reel description — OWL reads it.", kind: "live", invoke: "open inbox", group: "Social" },
  { id: "reel-reader", name: "Reel Reader", blurb: "Analyzes tone, hook, and whether a reel is worth your time.", kind: "mind", invoke: "open inbox", group: "Social" },
  { id: "reply-mimic", name: "Reply Mimic", blurb: "Drafts a reply that sounds like you, not like a corporate bot.", kind: "mind", invoke: "open inbox", group: "Social" },
  { id: "paper-door", name: "Paper Door", blurb: "Turns a messy thought into an email or message you can send yourself.", kind: "mind", invoke: "draft an email about tomorrow", group: "Social" },
  { id: "voiceprint", name: "Voiceprint Style", blurb: "Writes in the cadence of your past notes once you save a few.", kind: "mind", invoke: "write this like me", group: "Social" },
  { id: "people-index", name: "People Index", blurb: "A quiet ledger of names, relations, and how to introduce OWL to them.", kind: "live", invoke: "open memory", group: "Social" },
  { id: "intro-protocol", name: "Intro Protocol", blurb: "Gives a short intro of you — and of itself — to someone in front of the camera.", kind: "mind", invoke: "introduce yourself", group: "Social" },
  { id: "sentiment-talon", name: "Sentiment Talon", blurb: "Reads whether a pasted thread is warm, cold, or a trap.", kind: "mind", invoke: "open inbox", group: "Social" },
  { id: "thread-untangler", name: "Thread Untangler", blurb: "Collapses a long chat paste into decisions, asks, and open loops.", kind: "mind", invoke: "summarize this thread", group: "Social" },
  { id: "digital-shadow", name: "Digital Shadow", blurb: "Walks you through where a name or email tends to leave public traces — briefing, not hacking.", kind: "mind", invoke: "brief me on my digital footprint", group: "Social" },

  { id: "imagine-forge", name: "Imagine Forge", blurb: "Creates still images from a short prompt, in-app, no other site.", kind: "live", invoke: "open studio", group: "Make" },
  { id: "edit-alchemist", name: "Edit Alchemist", blurb: "Rewrites an image by instruction after you generate one.", kind: "live", invoke: "open studio", group: "Make" },
  { id: "clip-weaver", name: "Clip Weaver", blurb: "Starts a short generated clip from a prompt when you confirm the spend.", kind: "live", invoke: "open studio", group: "Make" },
  { id: "code-nest", name: "Code Nest", blurb: "Writes code on request and can run JavaScript in a sandboxed perch.", kind: "live", invoke: "open code", group: "Make" },
  { id: "site-spindle", name: "Site Spindle", blurb: "Spins a full-page website preview from one sentence.", kind: "live", invoke: "open site", group: "Make" },
  { id: "songwright", name: "Songwright", blurb: "Composes original roost scores with oscillators — nothing licensed in.", kind: "live", invoke: "play moon circuit", group: "Make" },
  { id: "theme-shift", name: "Theme Shift", blurb: "Molt the HUD: night, frost, ember — one command, no settings hunt.", kind: "live", invoke: "hud frost", group: "Make" },
  { id: "glyphsmith", name: "Glyphsmith", blurb: "Designs marks, icons, and wordmarks as image prompts tuned for symbols.", kind: "mind", invoke: "design a mark for OWL", group: "Make" },
  { id: "storyboard", name: "Storyboard Loom", blurb: "Breaks a clip idea into shots you can generate one by one.", kind: "mind", invoke: "storyboard a 6 second owl intro", group: "Make" },
  { id: "constraint-forge", name: "Constraint Forge", blurb: "Writes code against rules you name, then explains how it satisfies them.", kind: "mind", invoke: "write python that must handle empty lists", group: "Make" },

  { id: "typo-oracle", name: "Typo Oracle", blurb: "Understands s[eelling, smashed words, and the hundred ways you miss a command.", kind: "live", invoke: "unlok al three divices", group: "Mind" },
  { id: "research-helix", name: "Research Helix", blurb: "Slows down, thinks in a verse, then returns a structured briefing.", kind: "mind", invoke: "who is Elon Musk", group: "Mind" },
  { id: "math-crucible", name: "Math Crucible", blurb: "Works multi-step math in the open, not a one-line guess.", kind: "mind", invoke: "solve 17^7 - 3 and show steps", group: "Mind" },
  { id: "law-of-forms", name: "Law of Forms", blurb: "Checks logic, proofs, and 'does this argument actually hold'.", kind: "mind", invoke: "check this reasoning", group: "Mind" },
  { id: "memory-amber", name: "Memory Amber", blurb: "Keeps your name, song, people, and notes in this nest across visits.", kind: "live", invoke: "open memory", group: "Mind" },
  { id: "dream-buffer", name: "Dream Buffer", blurb: "A hollow for stray notes OWL can recall later in conversation.", kind: "live", invoke: "remember that I ship at dawn", group: "Mind" },
  { id: "nested-thought", name: "Nested Thought", blurb: "Shows a brief think state before speaking so you see the turn, not a stall.", kind: "live", invoke: "think carefully about this", group: "Mind" },
  { id: "self-review", name: "Self Review", blurb: "Reads generated code back and flags the first thing that would break.", kind: "mind", invoke: "review the last code", group: "Mind" },
  { id: "proof-nest", name: "Proof Nest", blurb: "Explains why an answer is right in the fewest honest steps.", kind: "mind", invoke: "prove that briefly", group: "Mind" },
  { id: "plan-lattice", name: "Plan Lattice", blurb: "Turns a vague want into ordered moves with first action named.", kind: "mind", invoke: "plan how to launch OWL as a product", group: "Mind" },

  { id: "partner-pulse", name: "Partner Pulse", blurb: "Does not always wait — greets, checks in, and asks what you are doing.", kind: "live", invoke: "stay with me", group: "Companion" },
  { id: "tease-circuit", name: "Tease Circuit", blurb: "Dry wit on purpose. Will needle you if you leave it hanging.", kind: "live", invoke: "tease me", group: "Companion" },
  { id: "joke-talon", name: "Joke Talon", blurb: "Jokes that sound like a partner, not a compiled list.", kind: "mind", invoke: "make a joke about owls who run operating systems", group: "Companion" },
  { id: "mirror-ask", name: "Mirror Ask", blurb: "Turns the floor: OWL interviews you with one good question at a time.", kind: "live", invoke: "ask me something", group: "Companion" },
  { id: "reverse-brief", name: "Reverse Brief", blurb: "Asks what you are building until it can restate it better than you did.", kind: "mind", invoke: "interview me about my project", group: "Companion" },
  { id: "auto-greet", name: "Hi, Boss", blurb: "Addresses you by the name you gave — Boss until you change it.", kind: "live", invoke: "call me Boss", group: "Companion" },
  { id: "roaming-familiar", name: "Roaming Familiar", blurb: "When the HUD sleeps, a miniature OWL walks the screen and waits.", kind: "live", invoke: "go to sleep", group: "Companion" },
  { id: "second-shadow", name: "Second Shadow", blurb: "Replicates a second familiar on the perch — a visible clone, not a fork bomb.", kind: "live", invoke: "replicate yourself", group: "Companion" },
  { id: "sleep-perch", name: "Sleep Perch", blurb: "Powers the main face down without killing the nest. Click the familiar to wake.", kind: "live", invoke: "go to sleep", group: "Companion" },
  { id: "boot-mythos", name: "First Light", blurb: "A boot rite: eyes open, name appears, you awaken it — not a spinner.", kind: "live", invoke: "awaken", group: "Companion" },

  { id: "arcade", name: "Arcade Reliquary", blurb: "Games that live inside OWL, launched by voice: snake, pong, perch.", kind: "live", invoke: "play a game", group: "Play" },
  { id: "signal-snake", name: "Signal Snake", blurb: "A night-circuit snake with keyboard and swipe, scored in the roost.", kind: "live", invoke: "play snake", group: "Play" },
  { id: "echo-pong", name: "Echo Pong", blurb: "A two-paddle night match OWL keeps time for.", kind: "live", invoke: "play pong", group: "Play" },
  { id: "perch-catch", name: "Perch Catch", blurb: "Tap to keep the familiar on the line — a one-button night game.", kind: "live", invoke: "play perch", group: "Play" },
  { id: "quiet-hours", name: "Quiet Hours", blurb: "Stops proactive talk. OWL still answers; it stops interrupting.", kind: "live", invoke: "quiet hours", group: "Play" },
  { id: "focus-ring", name: "Focus Ring", blurb: "Hides side panels so the face and the work are the only things lit.", kind: "live", invoke: "focus", group: "Play" },
  { id: "weatherless", name: "Weatherless Sky", blurb: "HUD follows the hour — cooler at night, a shade lighter after dawn.", kind: "live", invoke: "stay with me", group: "Play" },
  { id: "circadian", name: "Circadian HUD", blurb: "Greeting changes with local time: first light, afternoon, night watch.", kind: "live", invoke: "good evening", group: "Play" },
  { id: "clipboard-owl", name: "Clipboard Owl", blurb: "If you paste into chat, it treats it as material, not a command by accident.", kind: "live", invoke: "open inbox", group: "Play" },
  { id: "log-of-hours", name: "Log of Hours", blurb: "A cinematic activity log of every mesh beat and reply in this sitting.", kind: "live", invoke: "open mesh", group: "Play" },

  { id: "command-echo", name: "Command Echo", blurb: "Status is spoken in beats: Opening. Playing. Online.", kind: "live", invoke: "play song believer", group: "Kernel" },
  { id: "cinematic", name: "Cinematic Status", blurb: "Replies for system work are short, staged, and never a paragraph of UI talk.", kind: "live", invoke: "open instagram", group: "Kernel" },
  { id: "fuzzy-intent", name: "Fuzzy Intent", blurb: "Levenshtein-tolerant matching across a wide lattice of command variants.", kind: "live", invoke: "plz play favrite song on al devices", group: "Kernel" },
  { id: "evolve", name: "Evolve Directive", blurb: "Change personality, name, and HUD from a sentence — OWL rewrites its own roost settings.", kind: "live", invoke: "be more of a partner", group: "Kernel" },
  { id: "whisper-click", name: "Whisper Click", blurb: "Spoken module names open the matching panel as if you had clicked it.", kind: "live", invoke: "open studio", group: "Kernel" },
  { id: "auto-dock", name: "Auto Dock", blurb: "Sleep docks the face into the roaming miniature without a settings page.", kind: "live", invoke: "go to sleep", group: "Kernel" },
  { id: "typo-museum", name: "Typo Museum", blurb: "Stores misspellings you use so later matching leans your way.", kind: "live", invoke: "open memory", group: "Kernel" },
  { id: "nest-backup", name: "Nest Backup", blurb: "Export and restore memory as a file you keep.", kind: "live", invoke: "open memory", group: "Kernel" },
  { id: "silence-craft", name: "Silence Craft", blurb: "Knows a nod is enough. Short confirmations instead of essays.", kind: "live", invoke: "news", group: "Kernel" },
  { id: "panic-perch", name: "Panic Perch", blurb: "If you ask it to calm you, it drops tools and talks like a person.", kind: "mind", invoke: "I am spiraling, sit with me", group: "Kernel" },

  { id: "multilingual", name: "Multilingual Ear", blurb: "Accepts commands in any language the mind can parse, not English-only triggers.", kind: "mind", invoke: "abre el estudio", group: "Language" },
  { id: "shadow-grammar", name: "Shadow Grammar", blurb: "Rewrites text to a register you name: sharper, kinder, more you.", kind: "mind", invoke: "rewrite this sharper", group: "Language" },
  { id: "briefing-nest", name: "Briefing Nest", blurb: "Summaries with a headline, three points, and the thing you should do next.", kind: "mind", invoke: "brief this", group: "Language" },
  { id: "debate-twin", name: "Debate Twin", blurb: "Argues the other side for one minute so you can hear the hole.", kind: "mind", invoke: "argue against this plan", group: "Language" },
  { id: "deadline-crow", name: "Deadline Crow", blurb: "Turns a goal into a sequence with times if you give it a date.", kind: "mind", invoke: "I need this Friday, plan it", group: "Language" },
  { id: "habit-trace", name: "Habit Trace", blurb: "Remembers a rhythm you declare — shipping hours, gym, writing — and asks later.", kind: "live", invoke: "remember I write at 6am", group: "Language" },
  { id: "name-remember", name: "Name Remember", blurb: "One sentence to rename yourself in the nest.", kind: "live", invoke: "call me Captain", group: "Language" },
  { id: "recall-thread", name: "Recall Thread", blurb: "Pulls what you told it earlier in the sitting without making you scroll.", kind: "mind", invoke: "what did I ask you to remember", group: "Language" },
  { id: "ask-anything", name: "Open Perch", blurb: "Ordinary questions, code, essays — the full mind, not a command-only toy.", kind: "mind", invoke: "what is the Fermi paradox in one page", group: "Language" },
  { id: "codex-grimoire", name: "Kernel Codex", blurb: "One hundred named abilities, invokable from a grimoire, not buried in a help page.", kind: "live", invoke: "open codex", group: "Language" },

  { id: "check-in", name: "Watchful Idle", blurb: "After a quiet spell, a small check-in — never an API storm, never on first paint.", kind: "live", invoke: "stay with me", group: "Time" },
  { id: "hours-clock", name: "Clock of Hours", blurb: "Time sits in the HUD in tabular numerals, always.", kind: "live", invoke: "what time is it", group: "Time" },
  { id: "first-question", name: "First Question", blurb: "On waking, OWL can ask what you are actually doing today.", kind: "live", invoke: "what should I do first", group: "Time" },
  { id: "notes-hollow", name: "Notes Hollow", blurb: "Scratch notes beside memory, retrieved by 'what did I jot down'.", kind: "live", invoke: "open memory", group: "Time" },
  { id: "hud-molt", name: "HUD Molt", blurb: "Layout can hide the mesh and keep only face, log, and voice.", kind: "live", invoke: "focus", group: "Time" },
  { id: "eq-beak", name: "Beak Equalizer", blurb: "Tiny bars under the beak while OWL speaks so the face is doing the talking.", kind: "live", invoke: "speak your next reply", group: "Time" },
  { id: "scan-rings", name: "Scan Rings", blurb: "Slow HUD rings around the head — orientation, not decoration soup.", kind: "live", invoke: "stay with me", group: "Time" },
  { id: "catchlight", name: "Catchlight", blurb: "A single specular in each pupil so the eyes read as wet glass, not stickers.", kind: "live", invoke: "look at me", group: "Time" },
  { id: "asymmetric-lid", name: "Asymmetric Lid", blurb: "Right lid lags the left so blinks feel biological.", kind: "live", invoke: "stay with me", group: "Time" },
  { id: "roost-export", name: "Roost Export", blurb: "Memory walks out as JSON. Nothing of yours stays only in a stranger's cloud.", kind: "live", invoke: "open memory", group: "Time" },
];

export const FEATURE_GROUPS = [
  "Presence",
  "Mesh",
  "Social",
  "Make",
  "Mind",
  "Companion",
  "Play",
  "Kernel",
  "Language",
  "Time",
] as const;
